### ISSUE TITLE
Crear un sistema de torns

### ISSUE THREAD

**Issue by jordiolivares** [EnginyeriaSofwareUB/ES2017F3#14]
Quan l'usuari acabi el seu torn (on torn en aquest cas direm que es quan acabi un temps per ara) ha de passar a un altre personatge

**Comment by arkeros** [comment]
Solved in https://github.com/EnginyeriaSofwareUB/ES2017F3/commit/0bb8cc941201a31d9af93f07c7934d3be84a6213
