### ISSUE TITLE
Fer un color hardcodejat per equip

### ISSUE THREAD

**Issue by jordiolivares** [EnginyeriaSofwareUB/ES2017F3#159]

**Comment by perecasxiru** [comment]
S'ha d'afegir a Main_Menu_integrated també!!!

**Comment by ctoujoma** [comment]
nomes seria cambiar el prefab 'show' del jugador, entre avui i dema ho tinc espero

**Comment by ctoujoma** [comment]
Estimat: 2h.
Real: 1'5h.

Astor.
