### ISSUE TITLE
Afegir un parell de predefinits per al mal i vida en el pregame

### ISSUE THREAD

**Issue by jordiolivares** [EnginyeriaSofwareUB/ES2017F3#175]

**Comment by OriolJG** [comment]
Ja he donat a ruben els dos modes de joc que tindrem, que son els seguents:
                                     * Normal               * Rapido
Turnos:                                  12                  6
Muñecos por equipo:              3                   2
Vida:                                       100               75
Multiplicador:                           1                  1
