### ISSUE TITLE
Fer que el personatge dispari

### ISSUE THREAD

**Issue by jordiolivares** [EnginyeriaSofwareUB/ES2017F3#2]
El personatge hauria de llençar un projectil que en impactar contra el terra es destrueixi el projectil

**Comment by maxby12** [comment]
Fixed with commit a10d1bead7a4bb2d85a9eed030446aa77df07af8

**Comment by maxby12** [comment]
Fixed in ffde7464f293bf743b47ac191ad0c27b9f05e64c
