### ISSUE TITLE
Retocar les físiques

### ISSUE THREAD

**Issue by perecasxiru** [EnginyeriaSofwareUB/ES2017F3#51]
- Reduïr tamany dels personatges ja que han de ser com la porta d'una casa coi
- Retocar el caminar perque funcioni
- A vegades salta a vegades no, arreglar això
- Que giri collons

**Comment by asterter5** [comment]
Estimat: 3h.

**Comment by asterter5** [comment]
Closed in 9es32ba0.
Real: 1h.
(Afegit un Material de fiiques als "DestructibleCubes", aixi podem controlar el "stickyness" del jugador amb el mapa)
