### ISSUE TITLE
Sincronitzar vent i núvols

### ISSUE THREAD

**Issue by perecasxiru** [EnginyeriaSofwareUB/ES2017F3#74]

**Comment by jordiolivares** [comment]
Estimat 1.5h

**Comment by ctoujoma** [comment]
done, faltaria tan sols posicionar els nubols el millor posible per a treure partit a que es vegi la sombra en el mapa i alhora els nubols per la part superior del cel

**Comment by perecasxiru** [comment]
Carles, has posat els nuvols darrera la camera.

**Comment by ctoujoma** [comment]
Just es el que comentava,  posicionar els nuvols a gusto del consumidor
