### ISSUE TITLE
Obtenir armes i munició

### ISSUE THREAD

**Issue by perecasxiru** [EnginyeriaSofwareUB/ES2017F3#77]
- [x] Fer el funcionament a GameController
- [x] Fer que actualitzi la GUI
- [x] Lligar les caixes de munició a això

**Comment by jordiolivares** [comment]
Tal i com ha dit l'Oriol al Discord:

podriem fer algunes armes basiques amb municio infinita
i despres algunes armes que nomes puguis agafar-les de caixes
1 caixa agafada = 1 us d'una arma random
per ex: cano, granada i espassa son gratis i infinites
arc i tnt son especials, no tenen us excepte si agafes de lterra

**Comment by jordiolivares** [comment]
Implementat el funcionament de limit d'usos: 1 hora

**Comment by perecasxiru** [comment]
Closed
