### ISSUE TITLE
Ajustar mal de les armes

### ISSUE THREAD

**Issue by maxby12** [EnginyeriaSofwareUB/ES2017F3#84]

**Comment by maxby12** [comment]
Fixed in f71af10c5deff6fb9329206f5498975d1c32f237
Algoritme de calcul del mal en funcio de la distancia es pot millorar més (es pot donar que explosio toqui model del Player pero el centre del Player no esta dins radi d'explosió).

**Comment by jordiolivares** [comment]
2 hores
