### ISSUE TITLE
Solucionar el bug de l'angle de disparar

### ISSUE THREAD

**Issue by jordiolivares** [EnginyeriaSofwareUB/ES2017F3#95]
Creiem que té a veure amb l'orientació del personatge

**Comment by maxby12** [comment]
Fixed in c28086f655ad2ea9ce0f4b7cf2d70e89f2e33291
Also blocked change to gun X when already equipped gun X

**Comment by maxby12** [comment]
Temps estimat: 30m

**Comment by maxby12** [comment]
Temps: 1h
